name: Java 11

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Azul JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
          cache: 'maven'
      - name: Setup with Blaze
        run: java -jar blaze.jar setup
      - name: Build with Maven
        run: mvn test
